name: flutter_application_1
description: A new Flutter project.
publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'  # Add this line

dependencies:
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  google_sign_in: ^6.3.0
  http: ^1.3.0  # Example dependency
  dio: ^5.0.0  # Replace with the latest version
  overlay_support: ^2.0.0  # Replace with the latest version
  shared_preferences: ^2.5.3
  flutter_inappwebview: ^6.1.5  # For content capture (optional)
  cloud_firestore: ^5.6.5

dependency_overrides:
  async: ^2.13.0
  fake_async: ^1.3.3
  leak_tracker: ^10.0.9
  material_color_utilities: ^0.12.0
  vm_service: ^15.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
