// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyPGt08dDiEDUHJyvevIuyAsKgdr9HRaU',
    appId: '1:535054396658:web:5f28ed4168a4d64b0ff46b',
    messagingSenderId: '535054396658',
    projectId: 'sol-3fc85',
    authDomain: 'sol-3fc85.firebaseapp.com',
    storageBucket: 'sol-3fc85.firebasestorage.app',
    measurementId: 'G-GEMF19B74Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-3-ueYYthL8UBqqJkXr3go9yhHVN-XWg',
    appId: '1:535054396658:android:83bfca851843955b0ff46b',
    messagingSenderId: '535054396658',
    projectId: 'sol-3fc85',
    storageBucket: 'sol-3fc85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaZl-vW6BAEEFnl8v3XL4JJXKKWMtqWqQ',
    appId: '1:535054396658:ios:035826b15cf830990ff46b',
    messagingSenderId: '535054396658',
    projectId: 'sol-3fc85',
    storageBucket: 'sol-3fc85.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaZl-vW6BAEEFnl8v3XL4JJXKKWMtqWqQ',
    appId: '1:535054396658:ios:035826b15cf830990ff46b',
    messagingSenderId: '535054396658',
    projectId: 'sol-3fc85',
    storageBucket: 'sol-3fc85.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyPGt08dDiEDUHJyvevIuyAsKgdr9HRaU',
    appId: '1:535054396658:web:d5f2a2687f3335b90ff46b',
    messagingSenderId: '535054396658',
    projectId: 'sol-3fc85',
    authDomain: 'sol-3fc85.firebaseapp.com',
    storageBucket: 'sol-3fc85.firebasestorage.app',
    measurementId: 'G-529YT3CNEJ',
  );
}
